# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, pypy2, pypy3]
        exclude:
          - os: macos-latest
            python-version: pypy2
          - os: macos-latest
            python-version: pypy3
          - os: windows-latest
            python-version: pypy2
          - os: windows-latest
            python-version: pypy3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --use-feature=2020-resolver -e .[test]
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        coverage run --branch --source src/ -m pytest --verbose utests/
    - name: Unit tests coverage
      run: |
        coverage report
        coverage xml
    - name: Update codecov for unit tests
      uses: codecov/codecov-action@v1.0.6
      with:
        flags: unit
        file: coverage.xml
    - name: Test with Robot Framework and coverage
      run: |
        coverage erase
        coverage run --branch --source src/ -m robot --exclude skip --pythonpath src --outputdir ./tests-report --consolecolors ansi atests
    - name: Acceptance tests coverage
      run: |
        coverage report
        coverage xml
    - name: Update codecov for acceptance tests
      uses: codecov/codecov-action@v1.0.6
      with:
        flags: acceptance
        file: coverage.xml
    - name: Archive Robot Framework Tests Report
      uses: actions/upload-artifact@v1
      with:
        name: rf-tests-report-${{ matrix.os }}-${{ matrix.python-version }}
        path: ./tests-report
